version: '3'

services:
  
  dominickbrasileiro-database:
    container_name: dominickbrasileiro-database
    build:
      context: ./mysql
      dockerfile: Dockerfile
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - dominickbrasileiro

  dominickbrasileiro-app:
    depends_on:
      - dominickbrasileiro-database
    container_name: dominickbrasileiro-app
    build:
      context: ./app
      dockerfile: Dockerfile
    entrypoint: |
      sh -c "/wait-for-it.sh dominickbrasileiro-database:3306 --strict --timeout=300 -- node src/index.js"
    networks:
      - dominickbrasileiro

  dominickbrasileiro-nginx:
    depends_on: 
      - dominickbrasileiro-app
    container_name: dominickbrasileiro-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - dominickbrasileiro

networks:
  dominickbrasileiro:
    driver: bridge

